import "./globals.css";
import { Inter } from "next/font/google";

export const metadata = {
  title: "My Next.js App",
  description: "Generated by Next.js",
};

// Load the regular Inter font
const inter = Inter({
  subsets: ["latin"],
});

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={inter.className}>
      <body>{children}</body>
    </html>
  );
}
